# Generated by Django 6.0 on 2025-12-07 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('content', models.JSONField()),
                ('source', models.CharField(max_length=255)),
                ('is_posted', models.BooleanField(default=False)),
            ],
        ),
    ]
