# Generated by Django 5.0.2 on 2024-02-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
